# Generated by Django 2.2.1 on 2022-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=70, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=70, verbose_name='Last Name')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=35, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=35, verbose_name='Mobile')),
                ('email1', models.EmailField(blank=True, max_length=50, verbose_name='Email 1')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
