# Generated by Django 2.2.1 on 2022-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
